# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4f9c1436ba38e0cb2e1df13c80936217828a287740204205dd6c27c65b3739e245429c5f022df4a043fed376ca3ea3e0530ef9064db617ba1a911e14a5530ff3

test:
  secret_key_base: 4680cb1b6f84e2220d635cd7d078254425d0e2e297b3010fc322ad50dc9391cea6e156b6078ce8b38190176c708f2077ac55f0556309a43ef707dfea68de0798

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
